### ISSUE TITLE
Versioning strategy?

### ISSUE THREAD

**Issue by subvertallchris** [daddyz/phonelib#146]
Thanks for your work on this gem, I'm very happy that it exists.

I see that you're currently at v0.6.26, which suggests to me a pre-release version, though it certainly appears stable and clearly is released. Just so we know how to setup our Gemfile to handle new releases, can you give an idea of how you handle version numbers? If I do `~> 0.6.26`, can I trust that there won't be breaking changes until you hit `0.7.0`?

Appreciate your help and thoughts.

**Comment by daddyz** [comment]
@subvertallchris I prefer not to do breaking changes at all ;)
Since its data needs to be updated regulary I am increasing last number on a monthly basis. Code doesn't get changed usually, maybe some tests are added depending on issues that were submitted by then. 
Middle number will be changed once some significant functionality will be added (like geo names or short numbers parsing data in the past).
If there will be any breaking change I will add a notification that will be popped up during gem installation (it happened once when strings were replaced by symbols).
And you are right, gem is pretty stable for a long time and it's still under 0.x.x version, and I don't know why I still didn't make it to be at least 1.0.0.
I say, you can be calm until v1 release for sure and after I will get to v1 just check release notes on releases page.
