### ISSUE TITLE
Phonelib.valid? returning inconsistent results for real US numbers in national format (without country prefix)

### ISSUE THREAD

**Issue by froodian** [daddyz/phonelib#163]
I don't quite understand why this is happening, but `Phonelib.valid?("(203) 451-7190")` returns true, but `Phonelib.valid?("(650) 253-0000")` returns false. They're both real US phone numbers. Is this expected behavior?

**Comment by daddyz** [comment]
@froodian It's because country is not specified. When you are not defining country, phonelib tries to guess by phone prefix, with second number it was detected as Singapore with prefix 65. First number was parsed as valid Egyptian number.
```ruby
Phonelib.parse("(203) 451-7190").country # => EG
Phonelib.parse("(650) 253-0000").country # => SG
```
But if you specify country for ```parse``` method or define a default country:
```ruby
Phonelib.default_country = 'US' # put this to initializer

Phonelib.valid?("(203) 451-7190") # => true
Phonelib.valid?("(650) 253-0000") # => true

Phonelib.parse("(203) 451-7190").country # => "US"
Phonelib.parse("(650) 253-0000").country # => "US"
```

**Comment by froodian** [comment]
I see, thank you for the clarification
