### ISSUE TITLE
When strict_check is true, e164 leaves white space

### ISSUE THREAD

**Issue by jonathanschoeller** [daddyz/phonelib#180]
Run the following
```ruby
Phonelib.strict_check = true
Phonelib.parse('+61 1300853440').e164
```

**Expected result**: `"+611300853440"`
**Observed result**: `"+61 1300853440"`

#### Notes 
- This behaviour seems to have changed between 0.6.30 and 0.6.31. In 0.6.30, the expected behaviour was observed.
- If `strict_check=false` we get the expected result.

**Comment by daddyz** [comment]
@jonathanschoeller There was a fix for strict_check in v0.6.31. Since you are passing number with space and strict_check is true, this number is not parsed as valid, so e164 is being returned as is. It's not really normalized e164, just the string that you passed. All formatting functions are returning provided string when number is not valid.
