### ISSUE TITLE
Validation does not support landline numbers

### ISSUE THREAD

**Issue by shqear93** [daddyz/phonelib#225]
I have tried to validate only landline number, using:

```ruby
  validates :phone_number, phone: { possible: true, types: [:landline] }
```

and I'm trying to validate this landline number 1-415-509-6995, but it gives me invalid phone number

**Comment by shqear93** [comment]
Just noticed that I was using the wrong type, it should be `:fixed_line` not `:landline`

But it's still weird that a landline number is treated as a mobile number
```ruby
  validates :phone_number, phone: { possible: true, types: [:mobile] }
```

(415) 509-6995 is still valid although it's landline

**Comment by shqear93** [comment]
Also it's not returning the carrier

```ruby

**Comment by daddyz** [comment]
@shqear93 sorry for really late response, as I know US numbering plan always resolved to fixed_or_mobile since there is no real option to differentiate fixed and mobile phone numbers. Libphonenumber uses this specia fixed_or_mobile in order to overcome this issue. And regarding carrier, it is taken from opensource DB, that may miss data.

**Comment by shqear93** [comment]
@daddyz thanks for your response, is there an option to set list of allowed types for each whitelisted country ?
