### ISSUE TITLE
`valid_countries` doesn't seems like working properly

### ISSUE THREAD

**Issue by shqear93** [daddyz/phonelib#236]
```
Phonelib Version: 0.6.51
Rails Version: 6.0.4
```

**My test case:**

Phone number: `6135550130` - Canadian

```ruby
Phonelib.parse('6135550130').valid_countries         #Empty Array
Phonelib.parse('6135550130').valid_for_country? 'CA' #true
Phonelib.parse('6135550130').countries               #["US"]
```

What is Expected:
```ruby
Phonelib.parse('6135550130').countries          #["US", "CA"]
Phonelib.parse('6135550130').valid_countries    #["CA"]
```

this might be valid only for canadian numbers

**Comment by daddyz** [comment]
@shqear93 Hi, what happens here, is that when you are not specifying country gem tries to guess it. And it can't guess to add "1" as country prefix. When you run ```Phonelib.parse('6135550130').valid_for_country? 'CA'``` gem executes ```Phonelib.parse('6135550130', :ca)```. You have several options here:
- you can define ```Phonelib.default_country``` to ```:ca```, in order to help gem to guess the country
- you can specify the country during parsing like ```Phonelib.parse('6135550130', :ca)```

**Comment by shqear93** [comment]
@daddyz Thanks for your response, I actually still confused about `valid_countries`, isn't supposed to try all possible countries?
