### ISSUE TITLE
Problem validating a French telephone with prefix +3369...

### ISSUE THREAD

**Issue by jfernandezrico** [daddyz/phonelib#246]
Hello,

I have an issue with a French phone number that starts with +3369. 
I could see that for +336[0..8] there is no problem. Maybe it's a new number and 69 are not added to the data yet.

Kind regards

**Comment by jfernandezrico** [comment]
Maybe it's not a valid prefix, and the good one is +59069.... which belongs to Guadalupe.

**Comment by aturay** [comment]
`Phonelib.add_additional_regex :fr, Phonelib::Core::MOBILE, '69\d{7}'`

**Comment by daddyz** [comment]
@aturay thanks for help.
@jfernandezrico yes, it's the only way to solve it right now, you can [open an issue for google libphonenumber team to fix the data](https://issuetracker.google.com/issues/new?component=192347&template=829703)

**Comment by n-b** [comment]
The `+33 6 9X XX XX XX` numbers are actually reserved for ultramarine territories (Guadeloupe, La Réunion, Martinique, Guyane, and Mmayotte). In phonelib, those are treated as different countries from FR. (Actually it’s in libphonenumber). (Actually actually, it’s in the [ARCEP Plan national de numérotation téléphonique](https://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf)).

I believe this is the same issue as [Puerto Rico](#75), and that the correct fix is to try multiple country codes instead of a single `default_country`. [I used to do exactly this](https://github.com/betagouv/rdv-solidarites.fr/pull/1481/files#diff-92b7d79a94e24e4cf32496ed263272324fb996d860b81e8bef9e6171d3f3e168R22-R36), but phonelib 0.7.0 that just came out seems to [allow several default_countries](https://github.com/daddyz/phonelib/issues/75#issuecomment-1149481557). Thants @daddyz !

**Comment by daddyz** [comment]
@n-b glad to hear that
