### ISSUE TITLE
Cannot parse Algeria mobile phone number

### ISSUE THREAD

**Issue by nicolasblanco** [daddyz/phonelib#40]
Hi, are you sure this gem include all the countries, currently trying to parse an Algerian mobile number (country ISO code is DZ), it does not parse:

    [10] pry(main)> phone = Phonelib.parse("0612345678", "DZ")
    => #<Phonelib::Phone:0x007fd8ae414680 @data={}, @national_number="0612345678", @original="0612345678">

Thanks.

**Comment by daddyz** [comment]
@nicolasblanco Look, gem's data is based on google libphonenumber, I am just taking their regexes.
You can try in their online demo in order to validate if gem is not working.
According to their regexes this number is possible but not valid. 
As I can see you are trying to parse mobile phone number, their valid regex tells that there should be 5, 6 or 9 coming after first 6 and not 1. This phone is valid: 0651234567.
