### ISSUE TITLE
Still a few issues with possible? number

### ISSUE THREAD

**Issue by saelen** [daddyz/phonelib#46]
require 'phonelib'

Phonelib.default_country = 'HK'
puts Phonelib.possible? '026875105'

Phonelib.default_country = 'US'
puts Phonelib.possible? '2503019'

Even with the new version, these return false however the google javascript / java implementation returns them as true.

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by daddyz** [comment]
@saelen Sorry for late response, I checked this and here is a summary.
US number can't be possible, it matches only with general possible pattern, but it is not possible for any of the country phone types. Google's library returns possible because of general possible pattern match, My library works in a different way, it must match against one of the phone type patterns in order to be valid or possible, that's why it is not detected as possible.
As for HK number you posted I added a fix.
