### ISSUE TITLE
Regression in country detection: leading digits

### ISSUE THREAD

**Issue by jarthod** [daddyz/phonelib#57]
I just upgraded from `0.4.5` to `0.4.9` and noticed a regression (it seems):
Taken this basic number that used to be detected correctly as a US number: `+17295470713`
It now says the country code is "AG", whereas this is just a small zone with numbers starting by "1-268".
So it seems to now take the first country matching the international prefix ("1") without taking care of the leading digits ("268" is **NOT** matching in this case).

```ruby
Phonelib.parse('+17295470713').country # => "AG"
```

I've temporarily rollbacked to `0.4.5`

**Comment by jarthod** [comment]
I've just bisected the version and it seems the bug was introduced beween `0.4.6` and `0.4.7`

**Comment by daddyz** [comment]
@jarthod I guess this number is not valid anymore, that's why it stopped showing US. Anyway I changed behaviour of ```country``` method to return country that is defined as main country for code and added method ```valid_country``` in case you will want to get valid country ISO code.
Please check this fix against master branch, this fix is still unreleased. I will release it in the near future.
Thanks for reporting.

**Comment by jarthod** [comment]
I just changed a digit (in the end) to obfuscate it but it's a valid number otherwise. And even if it's invalid there's no reason to return a country that definitely can't be :)
The fix seems to be working for me, thanks !
