### ISSUE TITLE
Canadian Area Codes

### ISSUE THREAD

**Issue by LaelWatkins** [daddyz/phonelib#67]
Some Canadian area codes don't result with a correctly formatted number.  Two examples are area codes are 306 and 416.  To test or recreate the issue, you can use 3065555555 or 4165555555.  Neither results in valid formatted phone numbers.

These are valid area codes.  Our code to create the formatted number:

  def clean_up_number
    phone = Phonelib.parse(number)
    return false if phone.blank?
    self.number = phone.extension.present? ? "#{phone.e164};#{phone.extension}" : phone.e164
    self.country_code = phone.country_code
    true
  end

Any suggestion would be greatly appreciated.   (We're using v 0.5.2, Rails 4.1.10)

**Comment by daddyz** [comment]
@LaelWatkins do you specify country for parsing? 
You can do it in ```parse``` method or just set globally ```Phonelib.default_country```.
I added tests for these numbers and they are passing, if specifying country.

**Comment by LaelWatkins** [comment]
We set it globablly.
<code>Phonelib.default_country = 'US'</code>

**Comment by daddyz** [comment]
Try to specify number with country prefix like '13065555555' instead of country and '3065555555'

**Comment by LaelWatkins** [comment]
Yes, this is work around we provide to our users. However, it's not consistent for all Canadian area codes.  We use this in a contact planning and tracking application.  Users easily have hundreds of contacts/connections.  Many won't know the country prefix for all of their contacts. 

Why does it format some and not others?  

The issue that I see for us is that these numbers are returned as invalid numbers. So after we parse these numbers, they fail validation. Adding the 1 allows it to pass. 

We'll update our code if necessary to retry with the one.  However, is it possible we'll experience this countries?  Is there any indication of known countries that this occurs?

**Comment by daddyz** [comment]
When you set default country and pass national number for parsing it virtually adds country prefix of country and tries to parse. If it fails, it tries to determine country by phone that you passed. So in case you are not passing "1" in the beginning it can validate your number against another country that matches.
Since you have both US and Canadian numbers you should use prefix 1 for all phones, so if the phone won't be valid in US, it will determine it will parse it as Canada and that would be the only country guess it can make.
Just to make clear, phone number 3065555555 is a possible number in Greece but 4165555555 is impossible number in Switzerland.
