### ISSUE TITLE
area_code is not working

### ISSUE THREAD

**Issue by stevesuh** [daddyz/phonelib#80]
I pulled down the latest gem 0.6.2 but it is not working in 0.5.5 either.  This is with my personal mobile but I'm getting same result with a different mobile as well.

[7] pry(main)> number = Phonelib.parse("+15306355653")
=> #<Phonelib::Phone:0x007f981a0ba6f8
 @data=
  {"US"=>
    {:id=>"US",
     :country_code=>"1",
     :international_prefix=>"011",
     :main_country_for_code=>"true",
     :national_prefix=>"1",
     :national_prefix_optional_when_formatting=>"true",
     :mobile_number_portable_region=>"true",
     :national=>"5306355653",
     :format=>{:pattern=>"(\\d{3})(\\d{3})(\\d{4})", :format=>"($1) $2-$3", :intl_format=>"$1-$2-$3"},
     :valid=>[:fixed_or_mobile],
     :possible=>[:premium_rate, :toll_free, :personal_number, :fixed_or_mobile]}},
 @extension="",
 @national_number="5306355653",
 @original="+15306355653",
 @sanitized="15306355653">
[8] pry(main)> number.possible?
=> true
[9] pry(main)> number.area_code
=> nil

**Comment by dmitry** [comment]
What it should return?

**Comment by dmitry** [comment]
Check out this file: https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

**Comment by stevesuh** [comment]
the area code 530.

**Comment by oogali** [comment]
@stevesuh @dmitry Apparently, libphonenumber works on parsing everything *except* US phone numbers.

In the above linked metadata file, there isn't a section defined for the United States.

And here's another GH issue where a Google contributor essentially tells you to pound sand and parse out the area code on your own. https://github.com/googlei18n/libphonenumber/issues/46

I'm afraid this issue can't be resolved because the underlying library doesn't natively have a way of doing so.

Theoretically, one could fork the Google repo and make a version of `PhoneNumberMetadata.xml` that contains definitions for the US, but maintaining that fork would get ... annoying.

**Comment by dmitry** [comment]
@oogali do you know better alternative than libphonenumber, may be paid?

**Comment by daddyz** [comment]
I am working on a fix for area_code method. Hope to roll it out next week

**Comment by daddyz** [comment]
@stevesuh @dmitry @oogali fixed the issue. Check against master or new release.
